### ISSUE TITLE
Release build issue

### ISSUE THREAD

**Issue by usamacpp** [firebase/boringSSL-SwiftPM#10]
I am utilizing this package into another Swift Package I build, it works fine when the target app is running in Debug config.
As soon as I make Release build some functionalities are missing.
I can share more details if needed

Generally my question is do I need specific settings for my Swift Package that consumes boringSSL-SwiftPM?

**Comment by paulb777** [comment]
Not that I know of. What is the issue you're seeing?

Note that this package is available here to support Firestore. We don't otherwise have official support.
